### ISSUE TITLE
span 태그에 data-ax-path를 설정하는 경우 스크립트 오류발생

### ISSUE THREAD

**Issue by hyunjun19** [thomasJang/AXBinder#2]
https://github.com/axisj/AXBinder/blob/gh-pages/src/AXBinder.js#L74 에서 `this.type`이 `undifined`로 나와서 오류 발생함.

**Comment by thomasJang** [comment]
span에 왜 그런짓을~~~

**Comment by hyunjun19** [comment]
그럼 텍스트는 어디에 바인딩해야 하나요~ =)

**Comment by thomasJang** [comment]
개선해야지머 ~~ ㅋㅋ

**Comment by hyunjun19** [comment]
https://github.com/axisj/AXBinder/pull/3 처음으로 pull request 날려봅니다~ =)

**Comment by hyunjun19** [comment]
https://github.com/axisj/AXBinder/commit/a4265bb5e6b3e30e9e9f3124e271fb683e2cac6d
